#!/usr/bin/env bash
set -euo pipefail

./get-protobuf
cd protobuf
cmake . \
  -DCMAKE_CXX_STANDARD=17 \
  -Dprotobuf_BUILD_CONFORMANCE=ON \
  -Dprotobuf_BUILD_TESTS=OFF

cmake --build . --target conformance_test_runner
cd ..
