;;; Generated by the protocol buffer compiler. DO NOT EDIT!
;;; source: google/protobuf/struct.proto

(define-message Struct
  (fields (map string (message Value)) 1))

(define-message Value
  (null_value (enum NullValue) 1)
  (number_value double 2)
  (string_value string 3)
  (bool_value bool 4)
  (struct_value (message Struct) 5)
  (list_value (message ListValue) 6))

(define-message ListValue
  (values (list (message Value)) 1))

(define-enum NullValue
  (NULL_VALUE 0))
