;;; Generated by the protocol buffer compiler. DO NOT EDIT!
;;; source: test_options.proto
;;; include: swish_options.proto

(define-message SpecialTypesMessage
  (repeated_double_list (list double) 1)
  (repeated_double_flvector (flvector double) 2)
  (repeated_float_flvector (flvector float) 3))

(define-message FlvectorValue
  (value (flvector double) 1))

(define-message Container
  (inner (message FlvectorValue) 1))
