;;; Generated by the protocol buffer compiler. DO NOT EDIT!
;;; source: google/protobuf/wrappers.proto

(define-message DoubleValue
  (value double 1))

(define-message FloatValue
  (value float 1))

(define-message Int64Value
  (value int64 1))

(define-message UInt64Value
  (value uint64 1))

(define-message Int32Value
  (value int32 1))

(define-message UInt32Value
  (value uint32 1))

(define-message BoolValue
  (value bool 1))

(define-message StringValue
  (value string 1))

(define-message BytesValue
  (value bytes 1))
